# Generated by Django 4.0 on 2021-12-19 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteTaking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('body', models.TextField()),
                ('tags', models.CharField(choices=[('office', 'office'), ('shopping', 'shopping'), ('holiday', 'holiday'), ('study', 'study'), ('personal', 'personal'), ('friends', 'friends'), ('home', 'home'), ('family', 'family')], default='personal', max_length=100)),
                ('visibility', models.CharField(choices=[('public', 'public'), ('private', 'private')], default='public', max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_taking', to='auth.user')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
